# Generated by Django 3.1.7 on 2022-01-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
